<?php
/**
 * @file
 * Leaflet Geofield integration.
 */

// @TODO follow-up if coordination with geofield necessary.
module_load_include('inc', 'leaflet_geofield', 'leaflet_geofield.formatters');
module_load_include('inc', 'geofield', 'leaflet_geofield.widgets');

/**
 * Implements hook_ctools_plugin_api().
 */
function leaflet_geofield_ctools_plugin_api($module, $api) {
  $path = drupal_get_path('module', 'leaflet_geofield') . '/includes';
  return array(
    'version' => 1,
    'path' => $path,
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function leaflet_geofield_ctools_plugin_directory($module, $plugin) {
  if ($module == 'leaflet') {
    return 'src/Leaflet/' . str_replace("\\", DIRECTORY_SEPARATOR, $plugin);
  }
}
