<?php
/**
 * @file
 * Leaflet module.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function leaflet_ctools_plugin_api($module, $api) {
  return array(
    'version' => 1,
    'path' => drupal_get_path('module', 'leaflet') . '/includes',
  );
}

/**
 * Implements hook_permission().
 */
function leaflet_permission() {
  return array(
    'administer leaflet' => array(
      'title' => t('Administer Leaflet'),
      'description' => t('Configure Leaflet settings and maps.'),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function leaflet_libraries_info() {
  $libraries['leaflet'] = array(
    'name' => 'Leaflet',
    'vendor url' => 'http://leafletjs.com/',
    'download url' => 'http://leaflet-cdn.s3.amazonaws.com/build/leaflet-0.7.3.zip',
    'version arguments' => array(
      'file' => 'leaflet-src.js',
      'pattern' => '@L.version = \'(.*)\'@',
      'lines' => 10,
    ),
    'files' => array(
      'js' => array(
        'leaflet.js' => array(
          'type' => 'file',
          'weight' => 6,
          'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
        ),
      ),
      'css' => array(
        'leaflet.css' => array(
          'type' => 'file',
          'weight' => 4,
          'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
        )
      ),
    ),
    'integration files' => array(
      'leaflet' => array(
        'js' => array(
          'js/leaflet.js' => array(
            'type' => 'file',
            'weight' => 8,
            'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
          ),
          'js/leaflet.pluginManager.js' => array(
            'type' => 'file',
            'weight' => 12,
            'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
          ),
          'js/leaflet.behaviors.js' => array(
            'type' => 'file',
            'weight' => 14,
            'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
          ),
        ),
      ),
    ),
    'variants' => array(
      'debug' => array(
        'files' => array(
          'js' => array(
            'leaflet-src.js' => array(
              'type' => 'file',
              'weight' => 2,
              'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
            ),
          ),
          'css' => array(
            'leaflet.css' => array(
              'type' => 'file',
              'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
            )
          ),
        ),
        'integration files' => array(
          'leaflet' => array(
            'js' => array(
              'js/leaflet.js' => array(
                'type' => 'file',
                'weight' => 8,
                'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
              ),
              'js/leaflet.pluginManager.js' => array(
                'type' => 'file',
                'weight' => 12,
                'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
              ),
              'js/leaflet.behaviors.js' => array(
                'type' => 'file',
                'weight' => 14,
                'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
              ),
              'js/leaflet.console.js' => array(
                'type' => 'file',
                'weight' => 16,
                'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
              ),
              'js/leaflet.debug.js' => array(
                'type' => 'file',
                'weight' => 18,
                'group' => \Drupal\leaflet\Config::get('leaflet.js_css.group'),
              ),
            ),
          ),
        ),
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_element_info().
 */
function leaflet_element_info() {
  return array(
    'leaflet' => array(
      '#input' => FALSE,
      '#tree' => TRUE,
      '#process' => array('leaflet_element_process_callback'),
      '#pre_render' => array('leaflet_element_prerender_callback'),
      '#theme_wrappers' => array('form_element'),
    ),
  );
}

/**
 * Process callback for the leaflet form element.
 *
 * Renders the map and returns the markup in an renderable array.
 */
function leaflet_element_process_callback($element, $form_state, $complete_form) {
  /* @var \Drupal\leaflet\Types\Map $map */
  if (($map = \Drupal\leaflet\Leaflet::load('Map', $element['#map'])) == TRUE) {
    $element['map'] = $map->build();
  }

  return $element;
}

/**
 * Pre render callback for the leaflet form element.
 */
function leaflet_element_prerender_callback($element) {
  if (empty($element['map'])) {
    /* @var \Drupal\leaflet\Types\Map $map */
    if (($map = \Drupal\leaflet\Leaflet::load('Map', $element['#map'])) == TRUE) {
      $element['map'] = $map->build();
    }
  }

  return $element;
}

/**
 * Implements hook_i18n_string_info().
 */
function leaflet_i18n_string_info() {
  $groups['leaflet'] = array(
    'title' => t('Leaflet'),
    'format' => TRUE,
  );
  return $groups;
}

/**
 * Translate a string using i18n_string, if available.
 *
 * @param string $name
 *   Textgroup and context glued with ':'.
 * @param string $default
 *   String in default language. Default language may or may not be English.
 * @param array $options
 *   An associative array of additional options, with the following keys:
 *   - langcode: the language code to translate to a language other than what is
 *     used to display the page; defaults to the current language
 *   - filter: filtering callback to apply to the translated string only
 *   - format: input format to apply to the translated string only
 *   - callback: callback to apply to the result (both to the translated or
 *     untranslated string)
 *   - update: whether to update source table; defaults to FALSE
 *   - translate: whether to return a translation; defaults to TRUE.
 *
 * @return string
 *   The translated string if i18n_string is available, the original otherwise.
 *
 * @see i18n_string()
 */
function leaflet_i18n_string($name, $default, $options = array()) {
  if (module_exists('i18n_string')) {
    $result = i18n_string($name, $default, $options);
  }
  else {
    $result = $default;
    $options += array(
      'format' => NULL,
      'sanitize' => FALSE,
    );
    if ($options['sanitize']) {
      $result = check_markup($result, $options['format']);
    }
  }

  return $result;
}

/**
 * Wrapper to update / create translation source for user defined strings.
 *
 * Wrapper around i18n_string_update() that ensures the module is available.
 *
 * @param string|array $name
 *   Array or string concatenated with ':' that contains textgroup and string
 *   context.
 * @param string $string
 *   Source string in default language. Default language may or may not be
 *   English. Array of key => string to update multiple strings at once.
 * @param array $options
 *   Array with additional options:
 *   - 'format', String format if the string has text format
 *   - 'messages', Whether to print out status messages.
 *
 * @return mixed
 *   Same return as from i18n_string_update()
 *
 * @see i18n_string_update()
 */
function leaflet_i18n_string_update($name, $string, $options = array()) {
  if (module_exists('i18n_string')) {
    return i18n_string_update($name, $string, $options);
  }
}

/**
 * Wrapper to remove source and translations for user defined string.
 *
 * Though for most strings the 'name' or 'string id' uniquely identifies that
 * string, there are some exceptions (like profile categories) for which we need
 * to use the source string itself as a search key.
 *
 * @param string $name
 *   String name.
 * @param string $string
 *   Optional source string (string in default language).
 * @param array $options
 *   Array of string properties to remove.
 *
 * @return mixed
 *   Same return as from i18n_string_remove()
 *
 * @see i18n_string_remove()
 */
function leaflet_i18n_string_remove($name, $string = NULL, $options = array()) {
  if (module_exists('i18n_string')) {
    return i18n_string_remove($name, $string, $options);
  }
}

/**
 * Form callback handler to prepare the developer dialog form.
 *
 * Prepares an object options form to be used in a frontend development dialog.
 *
 * @param array $form
 *   The form array - likely emtpy.
 * @param array $form_state
 *   The form state.
 * @param object $object
 *   The object that provides the options form. Has to have the public method
 *   optionsForms().
 *
 * @return array
 *   The populated form.
 *
 * @see \Drupal\leaflet\Plugin\Source\GeoJSON\GeoJSON::getJS()
 */
function leaflet_dev_dialog_form($form, $form_state, $object) {
  $object->optionsForm($form, $form_state);
  leaflet_dev_dialog_form_clean($form);
  return $form;
}

/**
 * Prepares a form structure to be added to a development dialog.
 *
 * Removes all JS related stuff.
 *
 * @param array $form
 *   The form array to prepare.
 */
function leaflet_dev_dialog_form_clean(array &$form) {
  foreach (element_children($form) as $key) {
    unset(
      $form[$key]['#states'],
      $form[$key]['#attached']
    );
    leaflet_dev_dialog_form_clean($form[$key]);
  }
}
