<?php
/**
 * @file
 * Leaflet Quicktabs Integration module.
 */

/**
 * Implements hook_quicktabs_contents().
 */
function leaflet_quicktabs_quicktabs_contents() {
  $info = array();
  $info['Leaflet-map'] = array(
    'path' => drupal_get_path('module', 'leaflet_quicktabs') . '/plugins/quicktabs',
    'handler' => array(
      'file' => 'LeafletMap.php',
      'class' => 'LeafletMap',
    ),
  );
  return $info;
}
