<?php
/**
 * @file
 * Leaflet Contextual Links module.
 */

function leaflet_contextual_links_leaflet_object_postprocess_alter(&$build, $context) {
  if (!user_access('administer leaflet')) {
    return FALSE;
  }

  if (!($context instanceof Drupal\leaflet\Types\MapInterface)) {
    return FALSE;
  }

  if ($context->getOption('contextualLinks', FALSE) == FALSE) {
    unset($build['contextual_links']);
    return FALSE;
  }

  $current_path = current_path();
  if ('system/ajax' == $current_path && isset($_SESSION['current_path'])) {
    $current_path = $_SESSION['current_path'];
  }

  $links = array(
    'leaflet' => array(
      'title' => 'Edit this map',
      'href' => 'admin/structure/leaflet/maps/list/' . $context->machine_name . '/edit',
      'query' => array(
        'destination' => $current_path,
      ),
    ),
  );

  $objects = $context->getCollection()->getFlatList(\Drupal\leaflet\Leaflet::getPluginTypes(array('map')));
  ksort($objects);

  foreach ($objects as $object) {
    $object_links = array();

    // Build contextual link for this object.
    $name = $object->name;
    if (empty($name)) {
      $name = $object->machine_name;
    }

    $object_links[$object->getType() . ':' . $object->machine_name] = array(
      'title' => t('Edit @object_name', array('@object_name' => $name)),
      'href' => 'admin/structure/leaflet/' . $object->getType() . 's/list/' . $object->machine_name . '/edit',
      'query' => array(
        'destination' => $current_path,
      ),
    );

    if (!empty($object_links)) {
      // Build contextual link title for this type.
      $links[$object->getType()] = array(
        'title' => '<strong>' . ucwords($object->getType() . 's') . '</strong>',
        'html' => TRUE,
      );
      $links += $object_links;
    }
  }

  $build['leaflet']['contextual_links'] = array(
    '#prefix' => '<div class="contextual-links-wrapper">',
    '#suffix' => '</div>',
    '#theme' => 'links__contextual',
    '#links' => $links,
    '#attributes' => array('class' => array('contextual-links')),
    '#attached' => array(
      'library' => array(array('contextual', 'contextual-links')),
    ),
  );
  $build['#attributes']['class'][] = 'contextual-links-region';
}

function leaflet_contextual_links_form_leaflet_map_form_settings_alter(&$form, &$form_state) {
  if (($map = \Drupal\leaflet\Leaflet::load('Map', $form_state['item'])) == TRUE) {

    $form['options']['ui']['contextualLinks'] = array(
      '#type' => 'checkbox',
      '#title' => 'Contextual links',
      '#description' => t('Enable contextual links on the map.'),
      '#default_value' => $map->getOption('contextualLinks', FALSE),
      '#parents' => array('options', 'contextualLinks'),
    );
  }
}
